apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflow-instances.d-clare.ai
spec:
  scope: Namespaced
  group: d-clare.ai
  names:
    plural: workflow-instances
    singular: workflow-instance
    kind: WorkflowInstance
    shortNames:
    - wfi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                input:
                  type: object
            status:
              type: object
          required:
            - spec
      subresources:
        status: {}