apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.d-clare.ai
spec:
  scope: Namespaced
  group: d-clare.ai
  names:
    plural: workflows
    singular: workflow
    kind: Workflow
    shortNames:
      - wf
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: {}
          required:
            - spec
      subresources:
        status: {}